version: '3'
services:
  web:
    stdin_open: true
    build: ./client
    ports:
      - 3000:3000
    restart: always
    volumes:
      - /app/client/node_modules
      - ./client:/app/client
    depends_on:
      - api
